kind: Service
apiVersion: v1
metadata: 
  name: images
  namespace: movie-store
spec:
  type: ClusterIP
  ports: 
  - port: 32000
    targetPort: 32000
---
kind: Endpoints
apiVersion: v1
metadata:
  name: images
  namespace: movie-store
subsets:
- addresses:
  - ip: 192.168.1.78
  ports:
  - port: 32000