kind: Service
apiVersion: v1
metadata: 
  name: kafka
  namespace: movie-store
spec:
  type: ClusterIP
  ports: 
  - port: 9092
    targetPort: 9092
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kafka
  namespace: movie-store
subsets:
- addresses:
  - ip: 192.168.1.78
  ports:
  - port: 9092