kind: Service
apiVersion: v1
metadata: 
  name: postgres
  namespace: movie-store
spec:
  type: ClusterIP
  ports: 
  - port: 5242
    targetPort: 5242
---
kind: Endpoints
apiVersion: v1
metadata:
  name: postgres
  namespace: movie-store
subsets:
- addresses:
  - ip: 192.168.1.78
  ports:
  - port: 5242