kind: Service
apiVersion: v1
metadata: 
  name: schemas
  namespace: movie-store
spec:
  type: ClusterIP
  ports: 
  - port: 8081
    targetPort: 8081
---
kind: Endpoints
apiVersion: v1
metadata:
  name: schemas
  namespace: movie-store
subsets:
- addresses:
  - ip: 192.168.1.78
  ports:
  - port: 8081