apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-upgrade-from-source
  namespace: movie-store
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: helm
spec:
  description: >-
    These tasks will install / upgrade a helm chart into your Kubernetes /
    OpenShift Cluster using Helm

  params:
    - name: chartsDirectory
      description: The directory in source that contains the helm chart
    - name: releaseVersion
      description: The helm release version in semantic versioning format
      default: "v1.0.0"
    - name: releaseName
      description: The helm release name
      default: "helm-release"
    - name: releaseNamespace
      description: The helm release namespace
      default: ""
    - name: overwriteValues
      description: "Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1"
      default: ""
    - name: helmVersion
      description: "Specify a specific helm version"
      default: "latest"
  workspaces:
    - name: source
  steps:
    - name: upgrade
      image: lachlanevenson/k8s-helm:$(inputs.params.helmVersion)
      workingDir: /workspace/source
      script: |
        echo Installing Helm chart for resource with tag $(inputs.params.overwriteValues)
        helm upgrade --install --wait --namespace "$(inputs.params.releaseNamespace)" \
          --version $(inputs.params.releaseVersion) $(inputs.params.releaseName) $(inputs.params.chartsDirectory) --debug --set "$(inputs.params.overwriteValues)"