apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: migrate-db
  namespace: movie-store
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: image-build
    tekton.dev/displayName: "Migrate Database"
spec:
  description: >-
    This task migrates a Postgres database with Flyway.
  params:
  - name: modulePath
    description: The full module path in the project, followed by ":". E.g. ":modules:ingester:" will point to the ingester module within the modules folder
    default: ""
  - name: directory
    description: The directory containing the app, relative to the source repository root
    default: .
  - name: cache
    description: The name of the volume for caching Gradle artifacts, local Maven repository, and base image layers
    default: empty-dir-volume
  - name: flywayUser
    description: User name for the database for flyway migration.
    default: ""
  - name: flywayJdbcUrl
    description: JDBC Url for the database for flyway migration.
    default: ""
  - name: flywayPassword
    type: string
    description: The secret resource name that has the database password for flyway migration
    default: ""
  workspaces:
  - name: source
  steps:
  - name: migrate
    image: gcr.io/cloud-builders/gradle
    script: |
      #!/bin/sh
      set -o errexit
      modulePath=$(params.modulePath)
      echo "Flyway migration running"
      echo "User: " $FLYWAY_USER
      echo "Pass: " $FLYWAY_PASSWORD
      echo "Password Resource: " $(params.flywayPassword)
      echo "JDBC Url: " $FLYWAY_URL
      gradle $modulePath:flywayMigrate \
        --stacktrace --console=plain \
        --gradle-user-home=$HOME/.gradle \
        -Dgradle.user.home=$HOME/.gradle \
        -Duser.home=$HOME
    workingDir: $(workspaces.source.path)/$(params.directory)
    env:
    - name: HOME
      value: /workspace
    - name: FLYWAY_USER
      value: $(params.flywayUser)
    - name: FLYWAY_EDITION
      value: community
    - name: FLYWAY_URL
      value: $(params.flywayJdbcUrl)
    - name: FLYWAY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: $(params.flywayPassword)
          key: password
    volumeMounts:
    # empty volume required to make the Gradle home globally writable
    - name: empty-dir-volume
      mountPath: /workspace/.gradle
      subPath: gradle-user-home
    - name: $(params.cache)
      mountPath: /workspace/.gradle/caches
      subPath: gradle-caches
    - name: $(params.cache)
      mountPath: /workspace/.gradle/wrapper
      subPath: gradle-wrapper
    - name: $(params.cache)
      mountPath: /workspace/.m2
      subPath: m2-cache
    securityContext:
      runAsUser: 0

  volumes:
  - name: empty-dir-volume
    emptyDir: {}