kind: Service
apiVersion: v1
metadata: 
  name: schemas
spec:
  type: ClusterIP
  ports: 
  - port: 8081
    targetPort: 8081
---
kind: Endpoints
apiVersion: v1
metadata:
  name: schemas
subsets:
- addresses:
  - ip: {{ .Values.schemaRegistryIp }}
  ports:
  - port: 8081