/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.3/userguide/multi_project_builds.html
 */

rootProject.name = "movies"

include(
    ":modules:moviecmd",
    ":modules:movies-domain",
    ":modules:ingester",
    ":modules:movies-consumer",
    ":modules:people-consumer"
)

project(":modules:moviecmd").name = "moviecmd"
project(":modules:movies-domain").name = "movies-domain"
project(":modules:ingester").name = "ingester"
project(":modules:movies-consumer").name = "movies-consumer"
project(":modules:people-consumer").name = "people-consumer"

pluginManagement {
    val kotlinVersion: String by settings

    plugins {
        application
        kotlin("jvm") version kotlinVersion
        id("org.jetbrains.kotlin.plugin.serialization") version kotlinVersion
    }
}
