apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tmdb-api-key
  namespace: movie-store
spec:
  encryptedData:
    apiKey: AgAv5Y6hUYh9vm+OW3mUXyswiyJeQkGAOh9qWPs4rdJuSPQkgElsa38/+A0/kQcUrL+DVVA2cMn3m0jAKCSnKdHugVzOfJ+UkiLeDjOH1G+PH8DsNkvFT7l42ubAwM6r1leOu0LyQK2uj4S/t6PEgigh2Z5eHEvUlmktgX+rMuwp071Dnu0T3Spakae+RV4f0H6qhvIGcZxJd2iC7UuIJ9OBfNTxJqrAr5g9MHCoa2jOKUUMgBpjwUCxyq9WKx8AaDogBPdvEepsyozhYcc9/u9mnNF4Vrx//UasE6PXW0uJAWxVBjdLOfPfGogrIkPsgU8na3W0JqUF4O/Zv6M6PQ2+6VKs/qiecz74pv03Ny2D934LWT082b9LheBvR/9KA0G4P3WNA5S0kRSmihSd6PcDqUTtgjCiP07bbYzfsmTwJ3mhU49hGWspyitZeGWJhj9egMYkJYGqBM8T7wcUJ54S9E8GZyRj1QlrnBvqrYqwsUJsmVZAb24MnHjbPwmG0yEWufHkixnt6CgDWFB7vgLC+iGxSd8gckLnzxItII+1ECnQ8+wumF8TFuKLQaZWbNPdfVb27SuonbprOQO6Cpt8/ChQFMlYs9HK4LsEOgczLEmlkXM/Rx2ZubWHphtD3djB2JMn/o9bC0nwaXuMthUj1wNcvH6QtEIeqs6kzB2RcOnza1z3h2xIR1tPHFtR2xlEbwb9zuRrbTBUWb8CNYDs/rKIixar0ylktelYpiv6Bw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tmdb-api-key
      namespace: movie-store

