imageRegistry: "localhost:32000"
imageTag: "0"
replicaCount: 1
kafka: 
    maxPollRecords: 100
    consumerGroupId: peopledb
    enableAutoCommit: false
    bootstrapServers: "PLAINTEXT://kafka.movie-store:9092"
    schemaRegistryUrl: "http://schemas.movie-store:8081"
topics:
    people: local.movies.fct.people.0
    deadLetters: local.movies.sys.people-errors.0
postgres:
    user: peopleservice
    database: people
    port: 5432
    host: 192.168.1.78
    maxPoolSize: 20