apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-ingester-pipeline
  namespace: movie-store
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/keremk/movie-gatherer
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: create-image
    taskRef:
      name: test-build
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: imageUrl
      value: "192.168.1.78:32000/ingester"
    - name: insecureRegistry
      value: "true"
    - name: modulePath
      value: ":modules:ingester:"  
    - name: testsFilter
      value: "com.codingventures.movies.ingester.tests.unit*"
  - name: deploy
    taskRef:
      name: helm-upgrade-from-source
    runAfter: 
    - create-image
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: chartsDirectory
      value: "./helm/movie-gatherer/charts/ingester"
    - name: overwriteValues
      value: "imageTag=$(tasks.create-image.results.tag)"
    - name: releaseNamespace
      value: "movie-store"
    - name: releaseName
      value: "ingester-service"    
