package dependencies

const val avroSerializerVersion = "5.3.3"
const val kotlinxSerializationVersion = "0.20.0"
const val coroutinesVersion = "1.3.3"
const val ktorVersion = "1.3.0"
const val kotestVersion = "4.1.1"
const val hopliteVersion = "1.1.5"
const val kafkaVersion = "2.4.0"
const val avro4kVersion = "0.30.0"
const val kotlinLogVersion = "1.7.9"
const val simpleLogVersion = "1.7.29"
const val cliktVersion = "2.6.0"
const val testContainersVersion = "1.14.3"
const val mockServerVersion = "5.10.0"
const val vertxVersion = "3.9.2"
const val kotlinPoetVersion = "1.6.0"
const val autoServiceVersion = "1.0-rc7"
const val flywayVersion = "6.5.5"
const val postgresVersion = "42.2.12"