imageRegistry: "localhost:32000"
imageTag: "0"
replicaCount: 1
tmdb:
    hostname: api.themoviedb.org
    maxNoPages: 100
    maxNoCrewRequests: 30
    maxNoCastRequests: 50
kafka: 
    maxPollRecords: 100
    consumerGroupId: movies-ingester
    enableAutoCommit: false
    bootstrapServers: "PLAINTEXT://kafka.movie-store:9092"
    schemaRegistryUrl: "http://schemas.movie-store:8081"
topics:
    tasks: local.movies.fct.tmdb-tasks.0
    people: local.movies.fct.people.0
    movies: local.movies.fct.movies.0
    deadLetters: local.movies.sys.tmdb-tasks-errors.0