imageRegistry: "images:32000"
imageTag: "0"
replicaCount: 1
tmdb:
    hostname: api.themoviedb.org
    maxNoPages: 1000
    maxNoCrewRequests: 500
    maxNoCastRequests: 500
kafka: 
    maxPollRecords: 100
    consumerGroupId: movies-ingester
    enableAutoCommit: false
    bootstrapServers: "PLAINTEXT://kafka:9092"
    schemaRegistryUrl: "http://schemas:8081"
topics:
    tasks: local.movies.fct.tmdb-tasks.0
    people: local.movies.fct.people.0
    movies: local.movies.fct.movies.0
    deadLetters: local.movies.sys.tmdb-tasks-errors.0