serverConfig:
  bootstrapServers: ${BOOTSTRAP_SERVERS_CONFIG}
  schemaRegistryUrl: ${SCHEMA_REGISTRY_URL}

consumerSettings:
  maxPollRecords: ${MAX_POLL_RECORDS}
  consumerGroupId: ${CONSUMER_GROUP_ID}
  enableAutoCommit: ${ENABLE_AUTO_COMMIT}
