serverConfig:
  bootstrapServers: ${BOOTSTRAP_SERVERS_CONFIG}
  schemaRegistryUrl: ${SCHEMA_REGISTRY_URL}

consumerConfig:
  maxPollRecords: ${MAX_POLL_RECORDS}
  consumerGroupId: ${CONSUMER_GROUP_ID}
  enableAutoCommit: ${ENABLE_AUTO_COMMIT}

kafkaTopics:
  tasks: ${TASKS_TOPIC}
  people: ${PEOPLE_TOPIC}
  movies: ${MOVIES_TOPIC}
  deadLetters: ${DEADLETTERS_TOPIC}