imageRegistry: "images:32000"
imageTag: "0"
replicaCount: 1
kafka: 
    maxPollRecords: 100
    consumerGroupId: moviesdb
    enableAutoCommit: false
    bootstrapServers: "PLAINTEXT://kafka:9092"
    schemaRegistryUrl: "http://schemas:8081"
topics:
    movies: local.movies.fct.movies.0
    deadLetters: local.movies.sys.movies-errors.0
postgres:
    user: movieservice
    database: movies
    port: 5432
    host: postgres
    maxPoolSize: 20

