apiVersion: v1
kind: ConfigMap
metadata:
  name: peopledb-config
  namespace: {{ .Release.Namespace }}
data:
  bootstrapServers: {{ quote .Values.kafka.bootstrapServers }}
  schemaRegistryUrl: {{ quote .Values.kafka.schemaRegistryUrl }}
  maxPollRecords: {{ quote .Values.kafka.maxPollRecords }}
  consumerGroupId: {{ .Values.kafka.consumerGroupId }}
  enableAutoCommit: {{ quote .Values.kafka.enableAutoCommit }}
  peopleTopic: {{ .Values.topics.people }}
  deadLettersTopic: {{ .Values.topics.deadLetters }}
  pgHost: {{ quote .Values.postgres.host }}
  pgPort: {{ quote .Values.postgres.port }}
  pgDatabase: {{ quote .Values.postgres.database }}
  pgMaxPoolSize: {{ quote .Values.postgres.maxPoolSize }}
  pgUser: {{ .Values.postgres.user }}
